import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import TransitDirections from '../src/components/TransitDirections'

import Container from '@mui/material/Container'
import Typography from '@mui/material/Typography'
import Box from '@mui/material/Box'
import Grid from '@mui/material/Grid'
import { Wrapper } from '@googlemaps/react-wrapper'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SDK Next Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          <a href="https://citymapper.com">Citymapper</a> SDK next
        </h3>
        <TransitDirections />
      </main>
    </div>
  )
}

export default function Index() {
  
  const render = (status: Status) => {
    return <h1>{status}</h1>
  }
  
  return (
    <Container maxWidth={false} disableGutters>
      <Wrapper apiKey={process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY} render={render} libraries={["places"]}>
        <TransitDirections/>
      </Wrapper>
    </Container>
  )
}
