name: Run SDK React Tests

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  publish-storybook:
    if: ${{ !github.event.pull_request.draft }}
    name: Run tests
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/sdk-react
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Storybook build requires node
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Node Packages
        run: yarn install --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Run tests for SDK React
        run: yarn test
        working-directory: ${{env.working-directory}}
