name: Remove Storybook PR

on:
  pull_request:
    types: [closed, unlabeled]
  workflow_dispatch:

jobs:
  remove-storybook:
    name: Remove Storybook
    if: "!contains(github.event.pull_request.labels.*.name, 'publish-preview')"
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/sdk-react
      pr_number: ${{ github.event.pull_request.number }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_KEY: ${{ secrets.S3_KEY }}
      INTERNAL_DOCS_URL: ${{ secrets.INTERNAL_DOCS_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CITYMAPPER_DOCS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CITYMAPPER_DOCS_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.CITYMAPPER_DOCS_AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.CITYMAPPER_DOCS_AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 900
      # AWS CLI requires Python
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install AWS CLI
        run: pip install awscli
      - name: Remove docs
        run: ./scripts/remove-storybook-pr.sh $pr_number
        working-directory: ${{env.working-directory}}
